version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: >
      sh -c "python create_database.py &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
      - ./.env:/app/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  fastapi:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - ./api:/app
      - ./.env:/app/.env
    ports:
      - "8001:8001"
    depends_on:
      - backend
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./.env:/app/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - fastapi
    env_file:
      - .env

volumes:
  postgres_data:
