# Generated by Django 4.2.7 on 2025-05-15 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expense",
            options={
                "ordering": ["-date"],
                "verbose_name": "Expense",
                "verbose_name_plural": "Expenses",
            },
        ),
    ]
