# Generated by Django 4.2.7 on 2025-05-15 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="apiusage",
            new_name="analytics_a_endpoin_069f50_idx",
            old_name="analytics_a_endpoin_9eb2a8_idx",
        ),
        migrations.RenameIndex(
            model_name="apiusage",
            new_name="analytics_a_user_id_84f158_idx",
            old_name="analytics_a_user_id_bc4f95_idx",
        ),
        migrations.RenameIndex(
            model_name="useractivity",
            new_name="analytics_u_user_id_54ee7d_idx",
            old_name="analytics_u_user_id_5d2c32_idx",
        ),
        migrations.RenameIndex(
            model_name="useractivity",
            new_name="analytics_u_activit_f59ac3_idx",
            old_name="analytics_u_activit_ccbf67_idx",
        ),
    ]
