# Generated by Django 4.2.7 on 2025-05-15 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "analytics",
            "0002_rename_analytics_a_endpoin_9eb2a8_idx_analytics_a_endpoin_069f50_idx_and_more",
        ),
    ]

    operations = []
