# Generated by Django 4.2.7 on 2025-05-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_name", models.CharField(default="EasyLaw", max_length=100)),
                ("default_timezone", models.CharField(default="UTC", max_length=100)),
                ("date_format", models.CharField(default="YYYY-MM-DD", max_length=50)),
                ("maintenance_mode", models.BooleanField(default=False)),
                ("allow_registrations", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "System Settings",
            },
        ),
    ]
