# Generated by Django 4.2.7 on 2025-05-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_portal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKeyStorage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key_name", models.CharField(max_length=100, unique=True)),
                ("encrypted_key", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "API Key",
                "verbose_name_plural": "API Keys",
            },
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="preferred_llm",
            field=models.CharField(
                choices=[("openai", "OpenAI"), ("gemini", "Gemini")],
                default="openai",
                max_length=20,
            ),
        ),
    ]
