# Generated by Django 4.2.11 on 2024-05-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FieldBoost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('farmer', 'farmer'), ('supplier', 'supplier')], default='farmer', max_length=35),
        ),
    ]
