# Generated by Django 5.1.3 on 2024-11-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FieldBoost", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("lawyer", "Lawyer"), ("client", "Client")],
                default="client",
                max_length=15,
            ),
        ),
    ]
