# Generated by Django 4.2.11 on 2024-08-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FieldBoost', '0002_customuser_groups_customuser_user_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='surname',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
