# Generated by Django 5.0.3 on 2024-05-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FieldBoost", "0002_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("farmer", "farmer"),
                    ("supplier", "supplier"),
                    ("driver", "driver"),
                ],
                default="farmer",
                max_length=35,
            ),
        ),
    ]
