# Generated by Django 5.0.3 on 2024-05-28 22:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FieldBoost", "0003_alter_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(default=django.utils.timezone.now, max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="surname",
            field=models.CharField(default="motsi", max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("farmer", "farmer"),
                    ("supplier", "supplier"),
                    ("driver", "driver"),
                ],
                default="farmer",
                max_length=15,
            ),
        ),
    ]
