# Generated by Django 4.2.11 on 2024-08-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FieldBoost', '0005_invoice_document_file_documentversion_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
