# Generated by Django 4.2.11 on 2024-08-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FieldBoost', '0007_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='storage_quota',
            field=models.BigIntegerField(default=5368709120),
        ),
    ]
