# Generated by Django 4.2.11 on 2024-08-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FieldBoost', '0013_alter_case_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
