# Generated by Django 4.2.11 on 2024-10-30 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FieldBoost', '0014_case_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='document',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='performed_by',
        ),
        migrations.RemoveField(
            model_name='casedocument',
            name='case',
        ),
        migrations.RemoveField(
            model_name='casedocument',
            name='document',
        ),
        migrations.RemoveField(
            model_name='casenote',
            name='author',
        ),
        migrations.RemoveField(
            model_name='casenote',
            name='case',
        ),
        migrations.RemoveField(
            model_name='casetask',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='casetask',
            name='case',
        ),
        migrations.RemoveField(
            model_name='compliancechecklist',
            name='case',
        ),
        migrations.AlterUniqueTogether(
            name='documentpermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='documentpermission',
            name='document',
        ),
        migrations.RemoveField(
            model_name='documentpermission',
            name='user',
        ),
        migrations.RemoveField(
            model_name='documentshare',
            name='document',
        ),
        migrations.RemoveField(
            model_name='documentshare',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='documentshare',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='documenttag',
            name='document',
        ),
        migrations.RemoveField(
            model_name='documenttag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='documentversion',
            name='document',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='client',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.RemoveField(
            model_name='case',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='storage_quota',
        ),
        migrations.RemoveField(
            model_name='document',
            name='content',
        ),
        migrations.RemoveField(
            model_name='document',
            name='is_template',
        ),
        migrations.AddField(
            model_name='case',
            name='risk_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='document',
            name='analysis_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='case',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='case',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Pending', 'Pending')], default='Open', max_length=50),
        ),
        migrations.AlterField(
            model_name='case',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('lawyer', 'Lawyer'), ('paralegal', 'Paralegal'), ('client', 'Client'), ('admin', 'Admin')], default='client', max_length=15),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.DeleteModel(
            name='CaseDocument',
        ),
        migrations.DeleteModel(
            name='CaseNote',
        ),
        migrations.DeleteModel(
            name='CaseTask',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='ComplianceChecklist',
        ),
        migrations.DeleteModel(
            name='DocumentPermission',
        ),
        migrations.DeleteModel(
            name='DocumentShare',
        ),
        migrations.DeleteModel(
            name='DocumentTag',
        ),
        migrations.DeleteModel(
            name='DocumentVersion',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
