# Generated by Django 4.2.11 on 2024-10-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FieldBoost', '0015_remove_auditlog_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='storage_quota',
            field=models.BigIntegerField(default=2147483648),
        ),
    ]
