# Generated by Django 4.2.11 on 2024-10-31 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FieldBoost', '0016_customuser_storage_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='recipient',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
