# Generated by Django 4.2.11 on 2024-11-04 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FieldBoost', '0023_evidence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='client',
        ),
        migrations.AddField(
            model_name='document',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='FieldBoost.case'),
        ),
    ]
