# Generated by Django 4.2.11 on 2024-11-04 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FieldBoost', '0025_document_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='FieldBoost.case'),
        ),
    ]
