# Generated by Django 4.2.11 on 2024-11-04 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FieldBoost', '0026_alter_evidence_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='FieldBoost.case'),
        ),
    ]
