# Generated by Django 4.2.11 on 2024-11-04 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FieldBoost', '0027_alter_document_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='FieldBoost.case'),
        ),
    ]
