# Generated by Django 4.2.7 on 2025-05-06 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "case_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("active", "Active"),
                            ("pending", "Pending"),
                            ("closed", "Closed"),
                            ("archived", "Archived"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("case_type", models.CharField(blank=True, max_length=100)),
                ("date_opened", models.DateField(auto_now_add=True)),
                ("date_closed", models.DateField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "assigned_attorneys",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={
                            "role__in": ["attorney", "paralegal", "admin"]
                        },
                        related_name="assigned_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cases",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_updated", "-date_opened"],
            },
        ),
    ]
